name: Build ESPSOFTWARE 26.2

on:
  push:
    branches:
      - "ver/26.2"
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository == 'Winds-Studio/Leaf' }}

    runs-on: ubuntu-24.04

    env:
      MC_VERSION: "26.2"
      BUILD_NUMBER: ${{ github.run_number }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true


      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: "21"
          cache: gradle


      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"


      - name: Grant Gradle permission
        run: |
          chmod +x gradlew


      - name: Apply patches
        run: |
          ./gradlew applyAllPatches \
          --stacktrace \
          --no-daemon


      - name: Create PaperclipJar
        run: |
          ./gradlew createPaperclipJar \
          --stacktrace \
          --no-daemon


      - name: Prepare release notes and artifacts
        run: |
          chmod +x ./scripts/prepareRelease.sh
          ./scripts/prepareRelease.sh

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          MC_VERSION: ${{ env.MC_VERSION }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}


      - name: Calculate SHA-256
        id: hash
        run: |
          FILE_NAME="leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar"

          HASH=$(sha256sum "$FILE_NAME" | awk '{print $1}')

          echo "sha256=$HASH" >> $GITHUB_OUTPUT


      - name: Release ESPSOFTWARE
        uses: softprops/action-gh-release@v2

        with:
          name: "ESPSOFTWARE ${{ env.MC_VERSION }}"
          tag_name: "ver-${{ env.MC_VERSION }}"

          files: |
            ./leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar

          body_path: ./release_notes.md

          token: ${{ secrets.GITHUB_TOKEN }}

          target_commitish: ${{ github.sha }}

          draft: false
          prerelease: false


      - name: Upload JAR to API
        uses: appleboy/scp-action@v1

        with:

          host: ${{ secrets.API_HOST }}

          username: ${{ secrets.API_USER }}

          password: ${{ secrets.API_PASS }}

          source: |
            ./leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar

          target: |
            ~/api/uploads/


      - name: Insert Build API

        uses: appleboy/ssh-action@v1

        with:

          host: ${{ secrets.API_HOST }}

          username: ${{ secrets.API_USER }}

          password: ${{ secrets.API_PASS }}


          script: |

            BRANCH="${{ github.ref_name }}"

            REPO_DIR="/root/Leaf-${BRANCH//\//-}"


            if [ -d "$REPO_DIR/.git" ]; then

              cd "$REPO_DIR"

              git fetch origin

              git checkout "$BRANCH"

              git reset --hard "origin/$BRANCH"

            else

              git clone \
              --branch "$BRANCH" \
              https://github.com/Winds-Studio/Leaf \
              "$REPO_DIR"

            fi


            cd ~/api/cli


            node insertBuild.js \
              --projectName leaf \
              --projectFriendlyName "ESPSOFTWARE" \
              --version ${{ env.MC_VERSION }} \
              --versionGroupName ${{ env.MC_VERSION }} \
              --versionName ${{ env.MC_VERSION }} \
              --build-number ${{ env.BUILD_NUMBER }} \
              --repositoryPath "$REPO_DIR" \
              --storagePath /root/api/storage \
              --download "primary:/root/api/uploads/leaf-${{ env.MC_VERSION }}-${{ env.BUILD_NUMBER }}.jar:${{ steps.hash.outputs.sha256 }}" \
              --buildChannel experimental
